version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=
            - MYSQL_USER=
            - MYSQL_PASSWORD=
        ports:
            - '3306:3306'
