version: "3.5"

services:
  postgres:
    image: 'postgres:14.5-alpine'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data/postgres
      POSTGRES_DB: "teste_dev"
    volumes:
       - ./.docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    
    networks:
      - teste-network

networks: 
    teste-network:
      driver: bridge